name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: npm
      - run: npm ci
      - name: Linting check
        run: npm run lint
      - name: Security Audit
        run: npm audit --audit-level=high
      - name: Unit tests
        run: npm run test
      # E2E nur bei Bedarf aktivieren:
      # - name: E2E tests
      #   run: E2E_ENABLED=true npx playwright install --with-deps && E2E_ENABLED=true npm run test:e2e
